### PR TITLE
updated link to page /nos-forfaits

### PR DESCRIPTION
**Pull request by zarkonite**

### CODE REVIEW

**Comment by zarkonite** [comment]
Again, forgot the ticket # in the req. This one is #59.

**Comment by jansensan** [comment]
@zarkonite This change will be accepted for now, however in the future follow the contribution guideline for branch names and commit messages, otherwise the PR will be refused and will require corrections.

**Comment by jansensan** [comment]
@zarkonite Eesh actually, I will not merge this, it is targeting the `master`, and you should target `develop`.

Please correct the following and submit a new PR with your changes:

- Rename the branch so it follows the contributing guideline
- Correct your commit message so it follows the contributing guideline.
- Submit your PR targeting `develop`.

**Comment by zarkonite** [comment]
Don't know what targeting master means? I've followed the same procedures as before. dev.megapode.ca works fine, not sure what else to do other than renaming the branch?

**Pull request closed without merging**
